name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64
      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          registry: passiora-qr-bot.cr.cloud.ru
          username: ${{ secrets.HUB_USERNAME }}
          password: ${{ secrets.HUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          platforms: linux/amd64
          provenance: false
          labels: ${{ steps.meta.outputs.labels }}
          tags: passiora-qr-bot.cr.cloud.ru/passiora-qr-bot:latest